- hosts: pfsense
  tasks:
  - name: "Add Internal DNS out rule"
    pfsense_rule:
      name: 'Allow Internal DNS traffic out'
      action: pass
      interface: lan
      ipprotocol: inet
      protocol: udp
      source: 1.2.3.4
      destination: any:53
#      after: 'Allow proxies out'
      state: present
