- hosts: pfsense
  tasks:
  - name: "Add Internal DNS out rule"
    pfsense_rule:
      action: pass
      interface: lan
      ipprotocol: inet
      protocol: udp
      source: <#{vm_ip_address}>
      destination: any:53
#      after: 'Allow proxies out'
      state: present
